list:
  1:
    code: gluten
    strings:
      - mouka
      - mouku
      - mouky
      - lepek
      - lepku
      - lepkový
      - gluten
      - obilovin
      - obilná
      - obilné
      - pšenice
      - pšeničná
      - pšeničný
      - pšeničné
      - pšenici
      - pšeničnou
      - pčenice
      - kamut
      - žito
      - žita
      - žitná
      - žitný
      - žitné
      - žitnou
      - slad
      - sladová
      - slad
      - oves
      - ovsa
      - ovesné
      - ovesná
      - avenin
      - ječmen
      - ječný
      - ječná
      - ječné
      - ječmenný
      - špalda
      - špaldy
      - špaldový
      - špaldová
      - špaldové
      - śpaldová
      - semolina
      - semolinová
      - semolinové
      - kvasná kultura
      - kroupy
      - triticale
      - "00"
      - kuskus
      - cereálie
      - celozrnná
      - strouhanka
      - nudle
      - vloček
      - chlebový
      - křupinky
      - otruby
  2:
    code: crustaceans
    strings:
      - korýšů
      - korýše
      - krevety
      - kraba
      - krabí
      - kalmar
      - kalmár
      - kalamáry
      - hlavonožců
      - sépie
      - sépiový
      - chobotnice
  3:
    code: eggs
    strings:
      - vejce
      - vajec
      - vaječ
      - žloutek
      - žloutky
      - majonéza
      - bílek
      - bílky
  4:
    code: fish
    strings:
      - ryb
      - treska
      - tresky
      - tresek
      - tresčí
      - losos
      - sleď
      - sledě
      - makrela
      - makrely
      - sardel
      - sardele
      - jikry
      - tuňák
      - ančovičky
      - ančovičková
      - ančoviček
      - sardinka
      - sardinky
      - sardinely
      - šprot
      - šproty
      - pstruh
      - kapr
      - štika
      - nemipterus
      - pangasius
  5:
    code: peanuts
    strings:
      - arašídy
      - arašídů
      - arašidů
      - arašídová
      - arašídový
      - arašídové
  6:
    code: soybeans
    strings:
      - sója
      - sóju
      - soju
      - soja
      - sóji
      - soji
      - sójová
      - sójový
      - sójové
      - sojový
      - sojová
      - sojové
      - sójovou
      - lecitin
      - tofu
      - okara
      - boby
      - miso
  7:
    code: lactose
    strings:
      - laktóza
      - laktózy
      - laktózu
      - laktosa
      - laktózou
      - mléko
      - mléka
      - mléčné
      - mléčná
      - mléčný
      - mléčně
      - mlékem
      - mléčnou
      - mlékárenská
      - mlékárenské
      - plnotučné
      - máslo
      - máselný
      - sýr
      - syrovátka
      - syrovátky
      - syrovátkový
      - syrovátková
      - syrovátkové
      - máslové
      - podmáslí
      - smetana
      - smetany
      - smetanový
      - smetanová
      - smetanového
      - smetanou
      - tvaroh
      - kasein
      - kaseinát
      - mascarpone
      - jogurt
      - bílkovina
      - šlehačka
      - ementál
      - čedar
      - camembert
      - bifidobacterium
      - lactobacillus
      - tvarůžky
      - eidam
      - mozzarella
      - gouda
      - grana padano
      - roquefort
  8:
    code: nuts
    strings:
      - skořápkových
      - ořechy
      - ořechů
      - oříšky
      - oříšků
      - oříšková
      - ořechových
      - skořápkové
      - skořákové
      - mandle
      - mandlí
      - mandlový
      - mandlová
      - mandlové
      - lískové
      - lísková
      - lískových
      - vlašské
      - vlašská
      - vlašských
      - kešu
      - para
      - pistácie
      - pistácií
      - pistáciové
      - piniové
      - "lísko-oříškové"
      - lískooříškový
      - "mandlovo-lískoořechová"
      - muškátový oříšek
      - makadamové
      - pekanové
      - jádra
  9:
    code: celery
    strings:
      - celer
  10:
    code: mustard
    strings:
      - hořčice
      - hořčicí
      - hořčici
      - hořčičná
      - hořčičné
      - hořčicové
      - hořčičný
      - hořtičnou
  11:
    code: sesame
    strings:
      - sezam
  12:
    code: sulphurDioxide
    strings:
      - oxid
      - siřičitý
      - siričitý
      - siřičitého
      - siřičitan
      - siřičitany
      - siřičitanů
      - disiřičitan
      - disiričitan
      - disiřičan
      - hydrogensřičitan
      - sulfidu
      - sulfitový
      - sulfur
      - s02
      - so2
      - so₂
      - e211
      - e222
      - e224
  13:
    code: lupin
    strings:
      - vlčí bob
      - vlčího bobu
      - lupinová
      - lupinové
      - lupinový
      - lupinových
      - lupiny
  14:
    code: molluscs
    strings:
      - mušle
      - měkkýš
      - měkkýši
      - měkkýšů
      - měkkýše
      - ústřic
      - ústřicový
ignoreStrings:
  - "tučným písmem"
  - "tučně"
  - "tučně."
  - "*tučně vyznačen alergen."
  - "velkými písmeny"
  - "velkým písmem"
  - "velkým"
  - "písmem"
  - "výrobek může obsahovat stopy:"
  - "informace pro alergiky"
  - "informace pro alergiky:"
  - "alergeny jsou ve složení vyznačeny tučným písmem."
  - "alergenní složky"
  - "alergeny"
  - "aroma"
  - "výrobky"
  - "může obsahovat"
